USE SCHEMA SNOWFLAKE_INTELIGENCE_HOL.CORE;

CREATE OR REPLACE PROCEDURE GET_STOCK_PRICE(TICKER STRING, EXCHANGE STRING)
RETURNS FLOAT
LANGUAGE SQL
AS
$$
DECLARE
    stock_price FLOAT;
BEGIN
    stock_price := 185.88;
    RETURN stock_price;
END;
$$;